mu_dj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls', namespace='news'))



]
if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from news.views import news_views, news_detail_view, save_image_view

app_name = 'news'
urlpatterns = [
    path('post/<int:img_id>/', news_detail_view, name='detail'),
    path('', news_views, name='img'),
    path('save-image/', save_image_view, name='save_image'),
]

news/models.py
from django.db import models


class Img(models.Model):
    title = models.CharField(max_length=32, verbose_name='название')
    img = models.ImageField(upload_to='%Y/%m/%d/', verbose_name='картинка')
    date = models.DateTimeField(auto_now_add=True, verbose_name='дата')


    def __str__(self):
        return self.title
    class Meta:
        verbose_name='картинка'
        verbose_name_plural='картинки'
        ordering=['date', 'title']


class Comment(models.Model):
    author = models.CharField(max_length=64, verbose_name='автор')
    text = models.TextField(blank=False, verbose_name='текст')
    date = models.DateTimeField(auto_now_add=True, verbose_name='дата')
    img = models.ForeignKey(Img, on_delete=models.CASCADE, verbose_name='картинка', related_name='comments')

    def __str__(self):
        return self.text[:32]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-date',]

news/forms.py
from django import forms

from news.models import Comment, Img


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text')


class ImageForm(forms.ModelForm):
    class Meta:
        model = Img
        fields = ('title', 'img')

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from news.forms import CommentForm, ImageForm
from news.models import Img


def news_views(request):
    context = {'imgs': Img.objects.all() }
    return render(request, 'news/page_1.html', context)


def news_detail_view(request, img_id):
    detail = get_object_or_404(Img, id=img_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.img = detail
            comment.save()
            form = CommentForm()

    else:
        form = CommentForm()

    comment = detail.comments.all()
    context = {'img_detail': detail, 'comments': comment, 'form': form}
    return render(request, 'news/details.html', context)


def save_image_view(request):
    if request.method == 'POST':
        form = ImageForm(data=request.POST,
                         files=request.FILES) # files добавляется, когда мы передаём файлы
        print(form.fields)
        if form.is_valid():
            form.save()
            return redirect(reverse('news:img'))  # слева пространство имён, справа  название ссылки
    else:
        form = ImageForm()

    context = {'form': form}
    return render(request, 'news/save_image.html', context)

news/templates/news/details.html
{% extends 'root.html' %}
{% load thumbnail %}
{% block content %}
  <div>
    <h1>{{ img_detail.title }}</h1>
    <img src="{{img_detail.img.url}}">
    <p>{{ img_detail.date }}</p>
  </div>
  <div>
    {% for comment in comments %}
    <div style="border: 1px solid black;">
      <h3>{{ comment.author }}</h3>
      <p>{{ comment.text }}</p>
      <p>{{ comment.date }}</p>
    </div>
    {% endfor %}
    <form action="." method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="OK">
    </form>
  </div>
{% endblock %}

news/templates/news/page_1.html
{% extends 'root.html' %}
{% load thumbnail %}
{% block content %}
{% for img in imgs %}
    <a href="{% url 'news:detail' img.id %}">
        <div>
            <h1>{{ img.title }} </h1>
            {% thumbnail img.img '500x300' as im %}
            <img src="{{im.url}}">
            {% endthumbnail %}

        </div>
    </a>
{%endfor%}
{%endblock%}

news/templates/news/save_image.html
{% extends 'root.html' %}

{% block content %}
  <form action="." method="post" enctype="multipart/form-data">
    <!--enctype для того, чтобы сохранялись картинки и файлы-->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить" />
  </form>
{% endblock %}

templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{titilee|default:'страница'}}</title>
</head>
<body>
    <div >
        {% block content %}

        {%endblock%}
    </div>
</body>
</html>